(function(g){var window=this;var Npa=function(a,b){return g.Vb(a,b)},x5=function(){},Opa=function(a){if(a.yc&&"function"==typeof a.yc)return a.yc();
if(g.v(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},Ppa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Dd&&"function"==typeof a.Dd)var c=a.Dd();else if(a.yc&&"function"==typeof a.yc)c=void 0;else if(g.Ma(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=Opa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},y5=function(a){g.jn(a,"zx",g.ed());
return a},z5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.on(a.l,b,c)},A5=function(a){return(a=g.Ko(a))?new ActiveXObject(a):new XMLHttpRequest},B5=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},Qpa=function(a){return"content-type"==a.toLowerCase()},C5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Rpa=function(a){return g.Pd&&g.qd(9)&&g.Ga(a.timeout)&&g.Ea(a.ontimeout)},D5=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},E5=function(a,b){if(a.g){C5(a);
var c=a.g,d=a.O[0]?g.Ia:null;a.g=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},F5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;D5(a);E5(a)},G5=function(a){return a.g?a.g.readyState:0},H5=function(a){if(a.i&&"undefined"!=typeof g.yY)if(a.O[1]&&4==G5(a)&&2==a.getStatus())B5(a,"Local request error detected and ignored");
else if(a.D&&4==G5(a))g.Kg(a.Rv,0,a);else if(a.dispatchEvent("readystatechange"),4==G5(a)){B5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ug(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Spa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<G5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";D5(a)}}finally{E5(a)}}},I5=function(a){g.Uf.call(this);
this.headers=new g.Ym;this.M=a||null;this.i=!1;this.O=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.P=!1;this.A=0;this.B=null;this.Y="";this.I=this.R=!1},J5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Tpa=function(a,b){var c=[];
g.Vk(b,function(d){try{var e=g.Zo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Yo(e)&&c.push(d):c.push(d)},a);
return c},Upa=function(a,b){var c=Tpa(a,b);
(0,g.B)(c,function(d){g.Zo.prototype.remove.call(this,d)},a)},K5=function(a){if(a.Yc){if(a.Yc.locationOverrideToken)return{locationOverrideToken:a.Yc.locationOverrideToken};
if(null!=a.Yc.latitudeE7&&null!=a.Yc.longitudeE7)return{latitudeE7:a.Yc.latitudeE7,longitudeE7:a.Yc.longitudeE7}}return null},Vpa=function(a,b){g.$a(a,b)||a.push(b)},L5=function(a){var b=0,c;
for(c in a)b++;return b},M5=function(a,b){var c=b instanceof g.yc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},Wpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Xpa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Wpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Ypa=function(a,b,c,d){var e=new g.an(null,void 0);
a&&g.bn(e,a);b&&g.cn(e,b);c&&g.dn(e,c);d&&(e.i=d);return e},N5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Xpa(a)},O5=function(){this.g=[];
this.i=[]},P5=function(a,b){g.dq[a]=!0;
var c=g.bq();c&&c.publish.apply(c,arguments);g.dq[a]=!1},Q5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Ym;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Zpa(this,a.capabilities||""),$pa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Zpa=function(a,b){a.capabilities.clear();
(0,g.ae)(b.split(","),g.Ra(Npa,aqa)).forEach(function(c){a.capabilities.add(c)})},$pa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},R5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},S5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},T5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bqa=function(a){return new R5(a)},U5=function(a){return g.La(a)?(0,g.G)(a,bqa):[]},V5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},W5=function(a){return g.La(a)?"["+(0,g.G)(a,V5).join(",")+"]":"null"},X5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},cqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},Y5=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z5=function(a,b){return g.Xa(a,function(c){return S5(c,b)})},dqa=function(){var a=(0,g.tt)();
a&&Upa(a,a.g.cf(!0))},$5=function(){var a=g.wt("yt-remote-connected-devices")||[];
g.qb(a);return a},eqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},a6=function(a){g.vt("yt-remote-connected-devices",a,86400)},c6=function(){if(b6)return b6;
var a=g.wt("yt-remote-device-id");a||(a=X5(),g.vt("yt-remote-device-id",a,31536E3));for(var b=$5(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return b6=d},d6=function(){var a=$5(),b=c6();
g.$a(a,b);g.zt()&&g.sb(a,b);a=eqa(a);if(0==a.length)try{g.Us("remote_sid")}catch(c){}else try{g.Ts("remote_sid",a.join(","),-1)}catch(c){}},e6=function(){return g.wt("yt-remote-session-browser-channel")},f6=function(){return g.wt("yt-remote-local-screens")||[]},g6=function(){g.vt("yt-remote-lounge-token-expiration",!0,86400)},fqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(f6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.kj)(c,function(d){return!g.$a(b,d)})&&g6();
g.vt("yt-remote-local-screens",a,31536E3)},gqa=function(a,b){g.vt("yt-remote-session-browser-channel",a);
g.vt("yt-remote-session-screen-id",b);var c=$5(),d=c6();g.$a(c,d)||c.push(d);a6(c);d6()},h6=function(a){a||(g.xt("yt-remote-session-screen-id"),g.xt("yt-remote-session-video-id"));
d6();a=$5();g.cb(a,c6());a6(a)},j6=function(){if(!i6){var a=g.ip();
a&&(i6=new g.To(a))}return i6?!!i6.get("yt-remote-use-staging-server"):!1},k6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},l6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},n6=function(a){a.length?m6(a.shift(),function(){n6(a)}):o6()},hqa=function(a){return"chrome-extension://"+a+p6},m6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},o6=function(){var a=l6();
a&&a(!1,"No cast extension found")},q6=function(){if(iqa){var a=2,b=l6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;m6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",o6,c)}},jqa=function(){q6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);n6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+p6,"//www.gstatic.com/eureka/clank"+p6])},r6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Uc=b;this.u=(0,g.y)(this.OC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},s6=function(){},t6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.pn(this);this.i=new g.Jg;this.i.setInterval(250)},v6=function(a,b,c){a.Qh=1;
a.cg=y5(b.clone());a.mh=c;a.u=!0;u6(a,null)},w6=function(a,b,c,d,e){a.Qh=1;
a.cg=y5(b.clone());a.mh=null;a.u=c;e&&(a.Kz=!1);u6(a,d)},u6=function(a,b){a.ti=(0,g.D)();
x6(a);a.wg=a.cg.clone();z5(a.wg,"t",a.A);a.Nk=0;a.tc=a.g.jp(a.g.Ek()?b:null);0<a.Op&&(a.pn=new g.Jl((0,g.y)(a.SA,a,a.tc),a.Op));a.ba.da(a.tc,"readystatechange",a.vL);var c=a.Rg?g.cc(a.Rg):{};a.mh?(a.Yn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.wg,a.Yn,a.mh,c)):(a.Yn="GET",a.Kz&&!g.Rd&&(c.Connection="close"),a.tc.send(a.wg,a.Yn,null,c));a.g.ne(1)},E6=function(a,b,c){for(var d=!0;!a.Hg&&a.Nk<c.length;){var e=kqa(a,c);
if(e==y6){4==b&&(a.dg=4,z6(15),d=!1);break}else if(e==A6){a.dg=4;z6(16);d=!1;break}else B6(a,e)}4==b&&0==c.length&&(a.dg=1,z6(17),d=!1);a.se=a.se&&d;d||(C6(a),D6(a))},kqa=function(a,b){var c=a.Nk,d=b.indexOf("\n",c);
if(-1==d)return y6;c=Number(b.substring(c,d));if(isNaN(c))return A6;d+=1;if(d+c>b.length)return y6;var e=b.substr(d,c);a.Nk=d+c;return e},H6=function(a,b){a.ti=(0,g.D)();
x6(a);var c=b?window.location.hostname:"";a.wg=a.cg.clone();g.jn(a.wg,"DOMAIN",c);g.jn(a.wg,"t",a.A);try{a.we=new ActiveXObject("htmlfile")}catch(n){C6(a);a.dg=7;z6(22);D6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in F6)k=F6[l];else if(l in G6)k=F6[l]=G6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
F6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Uc(g.rc("b/12014412"),d+"</body></html>");a.we.open();a.we.write(g.Oc(c));a.we.close();a.we.parentWindow.m=(0,g.y)(a.QK,a);a.we.parentWindow.d=(0,g.y)(a.Qy,a,!0);a.we.parentWindow.rpcClose=(0,g.y)(a.Qy,a,!1);c=a.we.createElement("DIV");a.we.parentWindow.document.body.appendChild(c);d=g.Dc(a.wg.toString());d=g.ad(g.Ac(d));d=g.Uc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Vc(c,d);a.g.ne(1)},x6=function(a){a.Ws=(0,g.D)()+a.o;
I6(a,a.o)},I6=function(a,b){if(null!=a.Mi)throw Error("WatchDog timer not null");
a.Mi=J6((0,g.y)(a.aL,a),b)},K6=function(a){a.Mi&&(g.w.clearTimeout(a.Mi),a.Mi=null)},D6=function(a){a.g.Pv()||a.Hg||a.g.an(a)},C6=function(a){K6(a);
g.rf(a.pn);a.pn=null;a.i.stop();g.rn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.we&&(a.we=null)},B6=function(a,b){try{a.g.Ky(a,b),a.g.ne(4)}catch(c){}},M6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;L6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){M6(a,b,c,d,f)},f)})}},L6=function(a,b,c){var d=new Image;
d.onload=function(){try{N6(d),c(!0)}catch(e){}};
d.onerror=function(){try{N6(d),c(!1)}catch(e){}};
d.onabort=function(){try{N6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{N6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
M5(d,a)},N6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},O6=function(a){this.g=a;
this.i=new s6},Q6=function(a){var b=P6(a.g,a.Xi,"/mail/images/cleardot.gif");
y5(b);M6(b.toString(),5E3,(0,g.y)(a.ZB,a),3,2E3);a.ne(1)},S6=function(a){var b=a.g.F;
if(null!=b)z6(5),b?(z6(11),R6(a.g,a,!1)):(z6(12),R6(a.g,a,!0));else if(a.zd=new t6(a,void 0,void 0,void 0),a.zd.Rg=a.Mp,b=a.g,b=P6(b,b.Ek()?a.Dj:null,a.Np),z6(5),!g.Pd||g.rd(10))z5(b,"TYPE","xmlhttp"),w6(a.zd,b,!1,a.Dj,!1);else{z5(b,"TYPE","html");var c=a.zd;a=!!a.Dj;c.Qh=3;c.cg=y5(b.clone());H6(c,a)}},T6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new s6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},lqa=function(a,b){this.g=a;
this.map=b;this.context=null},U6=function(a){g.tf.call(this,"statevent",a)},V6=function(a,b){g.tf.call(this,"timingevent",a);
this.size=b},W6=function(a){g.tf.call(this,"serverreachability",a)},$6=function(a){X6(a);
if(3==a.g){var b=a.jk++,c=a.Nl.clone();g.jn(c,"SID",a.l);g.jn(c,"RID",b);g.jn(c,"TYPE","terminate");Y6(a,c);b=new t6(a,a.l,b,void 0);b.Qh=2;b.cg=y5(c.clone());M5(new Image,b.cg.toString());b.ti=(0,g.D)();x6(b)}Z6(a)},b7=function(a){a.rC(1,0);
a.Nl=P6(a,null,a.Lp);a7(a)},X6=function(a){a.Tf&&(a.Tf.abort(),a.Tf=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.ff&&(g.w.clearTimeout(a.ff),a.ff=null);c7(a);a.ud&&(a.ud.cancel(),a.ud=null);a.Yf&&(g.w.clearTimeout(a.Yf),a.Yf=null)},d7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new lqa(a.bH++,b));2!=a.g&&3!=a.g||a7(a)},a7=function(a){a.ud||a.Yf||(a.Yf=J6((0,g.y)(a.Py,a),0),a.Lh=0)},g7=function(a,b){if(1==a.g){if(!b){a.jk=Math.floor(1E5*Math.random());
var c=a.jk++,d=new t6(a,"",c,void 0);d.Rg=null;var e=e7(a),f=a.Nl.clone();g.jn(f,"RID",c);g.jn(f,"CVER","1");Y6(a,f);v6(d,f,e);a.ud=d;a.g=2}}else 3==a.g&&(b?f7(a,b):0==a.i.length||a.ud||f7(a))},f7=function(a,b){if(b)if(6<a.Ig){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.jk-1;var d=e7(a)}else c=b.B,d=b.mh;else c=a.jk++,d=e7(a);var e=a.Nl.clone();g.jn(e,"SID",a.l);g.jn(e,"RID",c);g.jn(e,"AID",a.Zh);Y6(a,e);c=new t6(a,a.l,c,a.Lh+1);c.Rg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ud=c;v6(c,e,d)},Y6=function(a,b){if(a.Sc){var c=a.Sc.vv();
c&&g.Kb(c,function(d,e){g.jn(b,e,d)})}},e7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ig&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ig?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},h7=function(a){a.Rb||a.ff||(a.B=1,a.ff=J6((0,g.y)(a.Oy,a),0),a.Fh=0)},j7=function(a){if(a.Rb||a.ff||3<=a.Fh)return!1;
a.B++;a.ff=J6((0,g.y)(a.Oy,a),i7(a,a.Fh));a.Fh++;return!0},R6=function(a,b,c){a.Wn=c;
a.Ee=b.tf;a.A||b7(a)},c7=function(a){null!=a.Mg&&(g.w.clearTimeout(a.Mg),a.Mg=null)},i7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},l7=function(a,b){if(2==b||9==b){var c=null;
a.Sc&&(c=null);var d=(0,g.y)(a.YL,a);c||(c=new g.an("//www.google.com/images/cleardot.gif"),y5(c));L6(c.toString(),1E4,d)}else z6(2);k7(a,b)},k7=function(a,b){a.g=0;
a.Sc&&a.Sc.wu(b);Z6(a);X6(a)},Z6=function(a){a.g=0;
a.Ee=-1;if(a.Sc)if(0==a.o.length&&0==a.i.length)a.Sc.Xo();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Sc.Xo(b)}},P6=function(a,b,c){var d=g.kn(c);
if(""!=d.g)b&&g.cn(d,b+"."+d.g),g.dn(d,d.u);else{var e=window.location;d=Ypa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.kj&&g.Kb(a.kj,function(f,k){g.jn(d,k,f)});
g.jn(d,"VER",a.Ig);Y6(a,d);return d},J6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},z6=function(a){m7.dispatchEvent(new U6(m7,a))},n7=function(){},mqa=function(a,b){this.action=a;
this.params=b||{}},o7=function(a,b){g.H.call(this);
this.g=new g.N(this.IK,0,this);g.I(this,this.g);this.Uc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},p7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.So;this.i=new o7(this.uM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},nqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Wn,sessionId:a.g.l,arrayId:a.g.Zh}},q7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&g7(a.g),$6(a.g));a.D=0},r7=function(a){return!!a.g&&3==a.g.g},oqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},s7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},t7=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.fh(c+b,{})},u7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),md:g.Ra(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wq(b,a)},pqa=function(){var a=v7;
w7();x7.push(a);y7(x7)},z7=function(a,b){w7();
var c=x7,d=qqa(a,String(b));0==c.length?rqa(d):(y7(c),(0,g.B)(c,function(e){e(d)}))},w7=function(){x7||(x7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",x7,void 0))},rqa=function(a){var b=(A7+1)%50;
A7=b;B7[b]=a;C7||(C7=49==b)},y7=function(a){var b=B7;
if(b[0]){var c=A7,d=C7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
B7=Array(50);A7=-1;C7=!1}},qqa=function(a,b){var c=((0,g.D)()-sqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},D7=function(a){g.P.call(this);
this.B=a;this.g=[]},E7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},tqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ae)(a.g,function(f){return!!Y5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=E7(a,b[d])||c;return c},uqa=function(a,b){var c=a.g.length;
a.g=(0,g.ae)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},F7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},H7=function(a){D7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;G7(this);this.info("Initializing with "+W5(this.g))},I7=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=t7(a.l,"/pairing/get_lounge_token_batch");
u7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.YC,a),(0,g.y)(a.XC,a))}},G7=function(a){var b=U5(f6());
b=(0,g.ae)(b,function(c){return!c.uuid});
return tqa(a,b)},J7=function(a,b){fqa((0,g.G)(a.g,T5));
b&&g6()},L7=function(a,b){g.P.call(this);
this.A=b;var c=g.wt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;K7("Initialized with "+g.Og(this.g))},M7=function(a,b,c){var d=t7(a.u,"/pairing/get_screen_availability");
u7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},N7=function(a,b){a:if(L5(b)!=L5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(K7("Updated online screens: "+g.Og(a.g)),a.g=b,a.N("screenChange"));vqa(a)},O7=function(a){isNaN(a.l)||g.aq(a.l);
a.l=g.Zp((0,g.y)(a.Wr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},K7=function(a){z7("OnlineScreenService",a)},P7=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},vqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.vt("yt-remote-online-screen-ids",a.join(","),60):g.xt("yt-remote-online-screen-ids")},Q7=function(a){D7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};wqa(this)},S7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Fd();if(k=(c?Z5(k,c):null)||Z5(k,b)){k.uuid=b;var l=R7(a,k);M7(a.i,l,function(m){e(m?l:null)})}else c?xqa(a,c,(0,g.y)(function(m){var n=R7(this,new R5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));M7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},T7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Wq(t7(a.A,"/pairing/get_lounge_token_batch"),e)},yqa=function(a){a.g=a.l.Fd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W5(a.g))},wqa=function(a){U7(a);
a.l=new H7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.hD,a));yqa(a);a.o=U5(g.wt("yt-remote-automatic-screen-cache")||[]);U7(a);a.info("Initializing automatic screens: "+W5(a.o));a.i=new L7(a.A,(0,g.y)(a.Fd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},R7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.vt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,T5)));U7(a);a.u[b.uuid]=b.id;g.vt("yt-remote-device-id-map",a.u,31536E3);return b},U7=function(a){a.u=g.wt("yt-remote-device-id-map")||{}},V7=function(a,b,c){g.P.call(this);
this.O=c;this.F=a;this.i=b;this.l=null},W7=function(a,b){z7(a.O,b)},X7=function(a,b){V7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.AM,this);this.u=(0,g.y)(this.lL,this);this.o=g.Zp((0,g.y)(function(){zqa(this,null)},this),12E4)},Aqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.y)(function(){W7(this,"Failed to send message: getMdxSessionStatus.")},a)):W7(a,"Sending yt message without session: "+g.Og(b))},zqa=function(a,b){g.aq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.bn,a),d=(0,g.y)(a.Id,a);a.Iv(b,c,d,5)}}else a.Id(Error("Waiting for session status timed out."))},Y7=function(a,b,c){V7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ia;this.A=NaN;this.I=(0,g.y)(this.DM,this);this.g=g.Ia},Bqa=function(a){a.g=a.F.XA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ia;
this.bn(b)},a),(0,g.y)(function(b){this.g=g.Ia;
this.Id(b)},a))},Cqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}j6()&&(b.env_useStageMdx=1);return g.dh(b)},Z7=function(a,b){V7.call(this,a,b,"ManualSession");
this.g=g.Zp((0,g.y)(this.bi,this,null),150)},$7=function(a,b,c,d){g.P.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.RJ,this)},Dqa=function(a,b){return b?g.Xa(a.l,function(c){return S5(b,c.label)},a):null},a8=function(a){z7("Controller",a)},v7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},b8=function(a){return a.u||!!a.l.length||!!a.g},c8=function(a,b,c){b!=a.g&&(g.rf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Ny,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.bi(null)):a.N("yt-remote-cast2-session-change",null))},Eqa=function(a){var b=a.i.WA(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&S5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Dqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Kqa=function(a,b,c,d,e,f,k){Fqa()?Gqa(b,e,f,k)&&(e8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Hqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Hqa(a,c):(f8("Failed to load cast API: "+m),g8(!1),e8(!1),g.xt("yt-remote-cast-available"),g.xt("yt-remote-cast-receiver"),Iqa(),c(!1))},d?g.lq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?jqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?o6():(q6(),n6(Jqa.map(hqa))))):d8("Cannot initialize because not running Chrome")},Iqa=function(){d8("dispose");
var a=h8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);Lqa(!1);g.gq(i8);i8.length=0},j8=function(){return!!g.wt("yt-remote-cast-installed")},Mqa=function(){var a=g.wt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Nqa=function(){d8("clearCurrentReceiver");
g.xt("yt-remote-cast-receiver")},Oqa=function(){return j8()?h8()?h8().getCastSession():(f8("getCastSelector: Cast is not initialized."),null):(f8("getCastSelector: Cast API is not installed!"),null)},l8=function(){j8()?h8()?k8()?(d8("Requesting cast selector."),h8().requestSession()):(d8("Wait for cast API to be ready to request the session."),i8.push(g.fq("yt-remote-cast2-api-ready",l8))):f8("requestCastSelector: Cast is not initialized."):f8("requestCastSelector: Cast API is not installed!")},m8=
function(a,b){k8()?h8().setConnectedScreenStatus(a,b):f8("setConnectedScreenStatus called before ready.")},Fqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.dx||a},Pqa=function(a,b){h8().init(a,b)},Gqa=function(a,b,c,d){var e=!1;
h8()||(a=new $7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.vt("yt-remote-cast-available",f);P5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){d8("onReceiverSelected: "+f.friendlyName);
g.vt("yt-remote-cast-receiver",f);P5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){d8("onReceiverResumed: "+f.friendlyName);
g.vt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){d8("onSessionChange: "+V5(f));
f||g.xt("yt-remote-cast-receiver");P5("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
d8("cloudview.createSingleton_: "+e);return e},h8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Hqa=function(a,b){g8(!0);
e8(!1);Pqa(a,function(c){c?(Lqa(!0),g.iq("yt-remote-cast2-api-ready")):(f8("Failed to initialize cast API."),g8(!1),g.xt("yt-remote-cast-available"),g.xt("yt-remote-cast-receiver"),Iqa());b(c)})},d8=function(a){z7("cloudview",a)},f8=function(a){z7("cloudview",a)},g8=function(a){d8("setCastInstalled_ "+a);
g.vt("yt-remote-cast-installed",a)},k8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Lqa=function(a){d8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},e8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},n8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ge=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},o8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ge=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},p8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},q8=function(a,b){a.B=b;
a.A=(0,g.D)()},r8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},s8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o8(a)},t8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ge;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},v8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new O5;this.l=this.i=null;this.F=(0,g.y)(this.LH,this);this.B=(0,g.y)(this.lk,this);this.D=(0,g.y)(this.KH,this);this.H=(0,g.y)(this.XH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Zs,this),Qqa(this))):c=3;0!=c&&(b?this.Zs(c):g.Zp((0,g.y)(function(){this.Zs(c)},this),0));
var d=Oqa();d&&u8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},w8=function(a){return new n8(a.o.getPlayerContextData())},Qqa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.OJ,b),this))},a)},Rqa=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},x8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},z8=function(a,b,c){var d=w8(a);
q8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){Rqa(a);
a.o.setPlayerContextData(t8(b));Qqa(a)},u8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.lk(null));
a.l=b;a.l&&(z7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.lk(a.l.media[0]))},Sqa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=w8(a);b.contentId!=d.videoId&&z7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;q8(d,a.i.getEstimatedTime());y8(a,d)}else z7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},C8=function(a,b,c){g.P.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.O=NaN;this.P=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.P.push(g.Vr(window,"beforeunload",(0,g.y)(this.RC,this)));this.i=[];this.Qa=new n8;this.V=b.id;this.g=Tqa(this,c);this.g.subscribe("handlerOpened",this.PH,this);this.g.subscribe("handlerClosed",this.MH,this);this.g.subscribe("handlerError",this.NH,this);this.g.subscribe("handlerMessage",this.OH,this);oqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.zt()&&g.vt("yt-remote-session-video-id",d)},this)},D8=function(a){z7("conn",a)},Tqa=function(a,b){return new p7(t7(a.na,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},Uqa=function(a){a.u=g.Zp((0,g.y)(function(){D8("Connecting timeout");
this.A(1)},a),2E4)},F8=function(a){g.aq(a.u);
a.u=NaN},G8=function(a){g.aq(a.O);
a.O=NaN},Vqa=function(a){H8(a);
a.I=g.Zp((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.aq(a.I);
a.I=NaN},Xqa=function(a,b){b&&(F8(a),G8(a));
b==(r7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),E8(a,1),I8(a,"getNowPlaying"),Wqa(a)):a.A(1)},Yqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Yb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},Zqa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;s8(a.Qa,c,d);a.N("remoteQueueChange")},ara=function(a,b){b.params=b.params||{};
Zqa(a,b);$qa(a,b);a.N("autoplayDismissed")},$qa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
q8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?Vqa(a):H8(a);a.N("remotePlayerChange")},bra=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);q8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},cra=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},dra=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},era=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ge="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},Wqa=function(a){g.aq(a.H);
a.H=g.Zp((0,g.y)(a.A,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.Og(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){D7.call(this,"ScreenServiceProxy");
this.Gc=a;this.i=[];this.i.push(this.Gc.$_s("screenChange",(0,g.y)(this.yM,this)));this.i.push(this.Gc.$_s("onlineScreenChange",(0,g.y)(this.sJ,this)))},jra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Rp("MDX_CONFIG")||b;dqa();d6();K8||(K8=new s7(b?b.loungeApiHost:void 0),j6()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",L8,void 0));fra();var c=M8();if(!c){var d=new Q7(K8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Kqa(a,d,function(m){m?N8()&&m8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){P5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Og(b)),P8.push(g.fq("yt-remote-cast2-availability-change",function(){P5("yt-remote-receiver-availability-change")})),P8.push(g.fq("yt-remote-cast2-receiver-selected",function(){Q8(null);
P5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-receiver-resumed",function(){P5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-session-change",gra)),P8.push(g.fq("yt-remote-connection-change",function(m){m?m8(N8(),"YouTube TV"):R8()||(m8(null,null),Nqa())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Og(a)),hra(a),c.start(),N8()||ira())},lra=function(){var a=kra();
j8()&&g.wt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},kra=function(){var a=M8().Gc.$_gos();
var b=T8();b&&U8()&&(Y5(a,b)||a.push(b));return cqa(a)},V8=function(){var a=mra();
!a&&j8()&&Mqa()&&(a={key:"cast-selector-receiver",name:Mqa()});return a},mra=function(){var a=kra(),b=T8();
b||(b=R8());return g.Xa(a,function(c){return b&&S5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Fd();return Z5(b,a)},gra=function(a){O8("remote.onCastSessionChange_: "+V5(a));
if(a){var b=T8();b&&b.id==a.id?m8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){k8()?h8().stopSession():f8("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){z7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},nra=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},ora=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||nra("");g.Ha("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?P5("yt-remote-connection-change",!1):!b&&a&&P5("yt-remote-connection-change",!0)},R8=function(){var a=g.zt();
if(!a)return null;var b=M8().Fd();return Z5(b,a)},X8=function(a,b){T8()&&T8();
nra(a.id);var c=new C8(K8,a,S8());c.connect(b,ora());c.subscribe("beforeDisconnect",function(d){P5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},ira=function(){var a=R8();
a?(O8("Resume connection to: "+V5(a)),X8(a,0)):(h6(),Nqa(),O8("Skipping connecting because no session screen found."))},fra=function(){var a=S8();
if(g.Yb(a)){a=c6();var b=g.wt("yt-remote-session-name")||"",c=g.wt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},hra=function(a){a?(g.vt("yt-remote-session-app",a.app),g.vt("yt-remote-session-name",a.name)):(g.xt("yt-remote-session-app"),g.xt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.hs(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.JI);this.l.K(b,"captionschanged",this.JH);this.l.K(b,"captionssettingschanged",this.kA);this.l.K(b,"videoplayerreset",this.cn);this.l.K(b,"mdxautoplaycancel",this.YB);this.P=this.l.K(b,"onVolumeChange",this.yy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Jy,this);c.subscribe("remotePlayerChange",this.nk,this);c.subscribe("remoteQueueChange",this.cn,this);c.subscribe("autoplayUpNext",this.ky,
this);c.subscribe("previousNextChange",this.Gy,this);c.subscribe("nowAutoplaying",this.Cy,this);c.subscribe("autoplayDismissed",this.jy,this);this.suggestion=null;this.F=new g.xC(64);this.o=new g.N(this.iA,500,this);g.I(this,this.o);this.A=new g.N(this.jA,1E3,this);g.I(this,this.A);this.I=new r6(this.hM,0,this);g.I(this,this.I);this.B={};this.O=new g.N(this.JA,1E3,this);g.I(this,this.O);this.H=new g.Jl(this.pF,1E3,this);g.I(this,this.H);this.M=g.Ia;this.kA();this.cn();this.nk()},b9=function(a,b){a.u.nd(b,
a.i.getVideoData().lengthSeconds)},pra=function(a){b9(a,0);
a.o.stop();c9(a,new g.xC(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.Yz(a.i.getVideoData(1).videoId,c);a.B=w8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.vf,K5(c));c9(a,new g.xC(1))},qra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{TP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return w8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.DC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.rK(a.i,d);a.F=b;rra(a.u,c,b)}},g9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.CP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.mQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);sra(this,g.nK(a))},sra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.BN("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):g.EC(b)||g.U(b,4)?g.BN("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.BN("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.UT.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.RK.call(this,a);
this.i={key:X5(),name:"\u6b64\u8ba1\u7b97\u673a"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.Yj=new g.xC(64);this.D=0;this.rm=-1;if(!g.jz(g.X(this.player))){a=this.player;var b=g.qD(a);b&&(b=b.Mm())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.DK(a,b.element,4)}},rra=function(a,b,c){a.Yj=c;
a.player.N("presentingplayerstatechange",new g.ED(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.vf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=K5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?
(Q8(d||null),k8()?h8().setLaunchParams(d||null):f8("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?P5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Fd(),(d=Z5(d,b.key))&&X8(d,1))}},Spa=/^https?$/i,tra=["POST",
"PUT"];g.A(I5,g.Uf);g.h=I5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.P=!1;this.i=!0;this.g=this.M?A5(this.M):A5(g.UY);this.O=this.M?this.M.getOptions():g.UY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Rv,this);try{x5(B5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){x5(B5(this,"Error opening Xhr: "+f.message));F5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Ppa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Dd(),Qpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(tra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{C5(this),0<this.A&&(this.I=Rpa(this.g),x5(B5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Sv,this)):this.B=g.Kg(this.Sv,this.A,this)),x5(B5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){x5(B5(this,"Send error: "+f.message)),F5(this,f)}};
g.h.Sv=function(){"undefined"!=typeof g.yY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,B5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(B5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),E5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),E5(this,!0));I5.Ha.T.call(this)};
g.h.Rv=function(){this.ea()||(this.V||this.D||this.o?H5(this):this.QJ())};
g.h.QJ=function(){H5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<G5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var G6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},F6={"'":"\\'"},ura={};g.h=O5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Bma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.yc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var aqa={XM:"atp",hP:"ska",WO:"que",wO:"mus",gP:"sus",NN:"dsp",dP:"seq"};Q5.prototype.Uf=function(){var a=new Q5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var i6,b6="",p6=k6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",iqa=k6("loadCastFramework")||k6("loadCastApplicationFramework"),Jqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(r6,g.H);g.h=r6.prototype;g.h.NC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Uc:this.za=g.Kg(this.u,this.Uc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();r6.Ha.T.call(this)};
g.h.OC=function(){this.l?(this.za=g.Kg(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};s6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
s6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=t6.prototype;g.h.Rg=null;g.h.se=!1;g.h.Mi=null;g.h.Ws=null;g.h.ti=null;g.h.Qh=null;g.h.cg=null;g.h.wg=null;g.h.mh=null;g.h.tc=null;g.h.Nk=0;g.h.we=null;g.h.Yn=null;g.h.dg=null;g.h.Ej=-1;g.h.Kz=!0;g.h.Hg=!1;g.h.Op=0;g.h.pn=null;var A6={},y6={};g.h=t6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.vL=function(a){a=a.target;var b=this.pn;b&&3==G5(a)?b.Aj():this.SA(a)};
g.h.SA=function(a){try{if(a==this.tc)a:{var b=G5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Pd&&!g.rd(10)||g.Rd&&!g.qd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!J5(this.tc))break a;this.Hg||4!=b||7==c||(8==c||0>=d?this.g.ne(3):this.g.ne(2));K6(this);var e=this.tc.getStatus();this.Ej=e;var f=J5(this.tc);(this.se=200==e)?(4==b&&C6(this),this.u?(E6(this,b,f),g.Fh&&this.se&&3==b&&(this.ba.da(this.i,"tick",this.rL),this.i.start())):B6(this,f),this.se&&!this.Hg&&(4==b?this.g.an(this):(this.se=
!1,x6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.dg=3,z6(13)):(this.dg=0,z6(14)),C6(this),D6(this))}}catch(k){this.tc&&J5(this.tc)}finally{}};
g.h.rL=function(){var a=G5(this.tc),b=J5(this.tc);this.Nk<b.length&&(K6(this),E6(this,a,b),this.se&&4!=a&&x6(this))};
g.h.QK=function(a){J6((0,g.y)(this.PK,this,a),0)};
g.h.PK=function(a){this.Hg||(K6(this),B6(this,a),x6(this))};
g.h.Qy=function(a){J6((0,g.y)(this.OK,this,a),0)};
g.h.OK=function(a){this.Hg||(C6(this),this.se=a,this.g.an(this),this.g.ne(4))};
g.h.cancel=function(){this.Hg=!0;C6(this)};
g.h.aL=function(){this.Mi=null;var a=(0,g.D)();0<=a-this.Ws?(2!=this.Qh&&this.g.ne(3),C6(this),this.dg=2,z6(18),D6(this)):I6(this,this.Ws-a)};
g.h.getLastError=function(){return this.dg};g.h=O6.prototype;g.h.Mp=null;g.h.zd=null;g.h.qn=!1;g.h.Qv=null;g.h.Ll=null;g.h.Dq=null;g.h.Np=null;g.h.Wd=null;g.h.tf=-1;g.h.Dj=null;g.h.Xi=null;g.h.connect=function(a){this.Np=a;a=P6(this.g,null,this.Np);z6(3);this.Qv=(0,g.D)();var b=this.g.D;null!=b?(this.Dj=b[0],(this.Xi=b[1])?(this.Wd=1,Q6(this)):(this.Wd=2,S6(this))):(z5(a,"MODE","init"),this.zd=new t6(this,void 0,void 0,void 0),this.zd.Rg=this.Mp,w6(this.zd,a,!1,null,!0),this.Wd=0)};
g.h.ZB=function(a){if(a)this.Wd=2,S6(this);else{z6(4);var b=this.g;b.Ee=b.Tf.tf;l7(b,9)}a&&this.ne(2)};
g.h.jp=function(a){return this.g.jp(a)};
g.h.abort=function(){this.zd&&(this.zd.cancel(),this.zd=null);this.tf=-1};
g.h.Pv=function(){return!1};
g.h.Ky=function(a,b){this.tf=a.Ej;if(0==this.Wd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.tf;l7(c,2);return}this.Dj=c[0];this.Xi=c[1]}else c=this.g,c.Ee=this.tf,l7(c,2);else if(2==this.Wd)if(this.qn)z6(7),this.Dq=(0,g.D)();else if("11111"==b){if(z6(6),this.qn=!0,this.Ll=(0,g.D)(),c=this.Ll-this.Qv,!g.Pd||g.rd(10)||500>c)this.tf=200,this.zd.cancel(),z6(12),R6(this.g,this,!0)}else z6(8),this.Ll=this.Dq=(0,g.D)(),this.qn=!1};
g.h.an=function(){this.tf=this.zd.Ej;if(this.zd.se)0==this.Wd?this.Xi?(this.Wd=1,Q6(this)):(this.Wd=2,S6(this)):2==this.Wd&&((!g.Pd||g.rd(10)?!this.qn:200>this.Dq-this.Ll)?(z6(11),R6(this.g,this,!1)):(z6(12),R6(this.g,this,!0)));else{0==this.Wd?z6(9):2==this.Wd&&z6(10);var a=this.g;this.zd.getLastError();a.Ee=this.tf;l7(a,2)}};
g.h.Ek=function(){return this.g.Ek()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ne=function(a){this.g.ne(a)};g.h=T6.prototype;g.h.kj=null;g.h.ud=null;g.h.Rb=null;g.h.Lp=null;g.h.Nl=null;g.h.nu=null;g.h.Wl=null;g.h.jk=0;g.h.bH=0;g.h.Sc=null;g.h.Yf=null;g.h.ff=null;g.h.Mg=null;g.h.Tf=null;g.h.Wn=null;g.h.Zh=-1;g.h.xw=-1;g.h.Ee=-1;g.h.Lh=0;g.h.Fh=0;g.h.Ig=8;var m7=new g.Uf;g.A(U6,g.tf);g.A(V6,g.tf);g.A(W6,g.tf);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){z6(0);this.Lp=b;this.kj=c||{};d&&g.Ea(e)&&(this.kj.OSID=d,this.kj.OAID=e);this.A?(J6((0,g.y)(this.Eu,this,a),100),b7(this)):this.Eu(a)};
g.h.Eu=function(a){this.Tf=new O6(this);this.Tf.Mp=null;this.Tf.i=this.u;this.Tf.connect(a)};
g.h.Pv=function(){return 0==this.g};
g.h.Py=function(a){this.Yf=null;g7(this,a)};
g.h.Oy=function(){this.ff=null;this.Rb=new t6(this,this.l,"rpc",this.B);this.Rb.Rg=null;this.Rb.Op=0;var a=this.nu.clone();g.jn(a,"RID","rpc");g.jn(a,"SID",this.l);g.jn(a,"CI",this.Wn?"0":"1");g.jn(a,"AID",this.Zh);Y6(this,a);if(!g.Pd||g.rd(10))g.jn(a,"TYPE","xmlhttp"),w6(this.Rb,a,!0,this.Wl,!1);else{g.jn(a,"TYPE","html");var b=this.Rb,c=!!this.Wl;b.Qh=3;b.cg=y5(a.clone());H6(b,c)}};
g.h.Ky=function(a,b){if(0!=this.g&&(this.Rb==a||this.ud==a))if(this.Ee=a.Ej,this.ud==a&&3==this.g)if(7<this.Ig){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.ff){if(this.Rb)if(this.Rb.ti+3E3<this.ud.ti)c7(this),this.Rb.cancel(),this.Rb=null;else break a;j7(this);z6(19)}}else this.xw=c[1],0<this.xw-this.Zh&&37500>c[2]&&this.Wn&&0==this.Fh&&!this.Mg&&(this.Mg=J6((0,g.y)(this.FH,this),6E3));else l7(this,11)}else b!=ura.sN.g&&l7(this,11);else if(this.Rb==a&&
c7(this),!g.wb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Zh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Wl=e[2],e=e[3],null!=e?this.Ig=e:this.Ig=6,this.g=3,this.Sc&&this.Sc.yu(),this.nu=P6(this,this.Ek()?this.Wl:null,this.Lp),h7(this)):"stop"==e[0]&&l7(this,7):3==this.g&&("stop"==e[0]?l7(this,7):"noop"!=e[0]&&this.Sc&&this.Sc.xu(e),this.Fh=0)}}};
g.h.FH=function(){null!=this.Mg&&(this.Mg=null,this.Rb.cancel(),this.Rb=null,j7(this),z6(20))};
g.h.an=function(a){if(this.Rb==a){c7(this);this.Rb=null;var b=2}else if(this.ud==a)this.ud=null,b=1;else return;this.Ee=a.Ej;if(0!=this.g)if(a.se)1==b?(b=(0,g.D)()-a.ti,m7.dispatchEvent(new V6(m7,a.mh?a.mh.length:0,b,this.Lh)),a7(this),this.o.length=0):h7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.ud||this.Yf||1==this.g||2<=this.Lh?d=!1:(this.Yf=J6((0,g.y)(this.Py,this,a),i7(this,this.Lh)),this.Lh++,d=!0);d=!(d||2==b&&j7(this))}if(d)switch(c){case 1:l7(this,
5);break;case 4:l7(this,10);break;case 3:l7(this,6);break;case 7:l7(this,12);break;default:l7(this,2)}}};
g.h.rC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.YL=function(a){a?z6(2):(z6(1),k7(this,8))};
g.h.jp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new I5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Sc&&this.Sc.isActive(this)};
g.h.ne=function(a){m7.dispatchEvent(new W6(m7,a))};
g.h.Ek=function(){return!(!g.Pd||g.rd(10))};
g.h=n7.prototype;g.h.yu=function(){};
g.h.xu=function(){};
g.h.wu=function(){};
g.h.Xo=function(){};
g.h.vv=function(){return{}};
g.h.isActive=function(){return!0};g.A(o7,g.H);g.h=o7.prototype;g.h.IK=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.xo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.A(p7,n7);g.h=p7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Bf=function(a){return this.l.Sg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.rf(this.l),q7(this),g.rf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Sc=null);d.Sc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Zh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):r7(this)&&d7(this.g,c)};
g.h.yu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)d7(this.g,a[b])}this.N("handlerOpened")};
g.h.wu=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Xo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.vv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.xu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),$6(this.g)):this.N("handlerMessage",new mqa(a[0],a[1]))};
g.h.uM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.ud&&b++;0!=b||this.connect(this.u,this.o)};s7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
s7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
s7.prototype.u=function(a){a(Error("request timed out"))};var sqa=(0,g.D)(),x7=null,B7=Array(50),A7=-1,C7=!1;g.A(D7,g.P);D7.prototype.Fd=function(){return this.g};
D7.prototype.contains=function(a){return!!Y5(this.g,a)};
D7.prototype.get=function(a){return a?Z5(this.g,a):null};
D7.prototype.info=function(a){z7(this.B,a)};g.A(F7,g.P);var vra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=F7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.VA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.aq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();F7.Ha.T.call(this)};
g.h.VA=function(){this.za=NaN;this.g=g.Wq(t7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.wM,this),onError:(0,g.y)(this.vM,this),md:(0,g.y)(this.xM,this)})};
g.h.wM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new R5(c))};
g.h.vM=function(a){this.g=null;a.status&&404==a.status?this.i>=vra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=vra[this.i],this.za=g.Zp((0,g.y)(this.VA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.xM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(H7,D7);g.h=H7.prototype;g.h.start=function(){G7(this)&&this.N("screenChange");!g.wt("yt-remote-lounge-token-expiration")&&I7(this);g.aq(this.i);this.i=g.Zp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){G7(this);E7(this,a);J7(this,!1);this.N("screenChange");b(a);a.token||I7(this)};
g.h.remove=function(a,b){var c=G7(this);uqa(this,a)&&(J7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Sn=function(a,b,c,d){var e=G7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,J7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.aq(this.i);H7.Ha.T.call(this)};
g.h.YC=function(a){G7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}J7(this,!b);b&&z7(this.B,"Missed "+b+" lounge tokens.")};
g.h.XC=function(a){z7(this.B,"Requesting lounge tokens failed: "+a)};g.A(L7,g.P);g.h=L7.prototype;g.h.start=function(){var a=parseInt(g.wt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?O7(this):(this.o=(0,g.D)()+3E5,g.vt("yt-remote-fast-check-period",this.o),this.Wr())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){K7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!Z5(a,d)},this);
N7(this,b)};
g.h.T=function(){g.aq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);L7.Ha.T.call(this)};
g.h.Wr=function(){g.aq(this.l);this.l=NaN;this.i&&this.i.abort();var a=P7(this);if(L5(a)){var b=t7(this.u,"/pairing/get_screen_availability");this.i=u7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.mK,this,a),(0,g.y)(this.lK,this))}else N7(this,{}),O7(this)};
g.h.mK=function(a,b){this.i=null;var c=g.Rb(P7(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;N7(this,d);O7(this)}else this.Jb("Changing Screen set during request."),this.Wr()};
g.h.lK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;O7(this)};
g.h.Jb=function(a){z7("OnlineScreenService",a)};g.A(Q7,D7);g.h=Q7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Sn=function(a,b,c,d){this.l.contains(a)?this.l.Sn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,z7(this.B,a),d(Error(a)))};
g.h.Fd=function(a){return a?this.g:g.fb(this.g,(0,g.ae)(this.o,function(b){return!this.contains(b)},this))};
g.h.WA=function(){return(0,g.ae)(this.Fd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.XA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new F7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.rf(f);d(R7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.rf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.zM=function(a,b,c,d){g.Wq(t7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new R5(f.screen||{});if(!k.name||T7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);T7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(R7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
md:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.rf(this.l);g.rf(this.i);Q7.Ha.T.call(this)};
g.h.hD=function(){yqa(this);this.N("screenChange");this.i.update()};
Q7.prototype.dispose=Q7.prototype.dispose;g.A(V7,g.P);g.h=V7.prototype;g.h.bn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Id=function(a){this.ea()||(a&&W7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){z7(this.O,a)};
g.h.ZA=function(){return null};
g.h.os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){W7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.os("");V7.Ha.T.call(this)};g.A(X7,V7);g.h=X7.prototype;g.h.ls=function(a){if(this.g){if(this.g==a)return;W7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Aqa(this)};
g.h.bi=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Id()},this),(0,g.y)(function(){this.Id(Error("Failed to stop receiver app."))},this)):this.Id(Error("Stopping cast device witout session."))};
g.h.os=g.Ia;g.h.T=function(){this.info("disposeInternal");g.aq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;X7.Ha.T.call(this)};
g.h.lL=function(a,b){if(!this.ea())if(b){var c=N5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":zqa(this,c.screenId);break;default:W7(this,"Unknown youtube message: "+d)}}else W7(this,"Unable to parse message.")}else W7(this,"No data in message.")};
g.h.Iv=function(a,b,c,d){S7(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(W7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zp((0,g.y)(this.Iv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.ZA=function(){return this.g};
g.h.AM=function(a){this.ea()||a||(W7(this,"Cast session died."),this.Id())};g.A(Y7,V7);g.h=Y7.prototype;g.h.ls=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.bi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.aq(this.A);this.o?this.o.stop((0,g.y)(this.Id,this,null),(0,g.y)(this.Id,this,"Failed to stop DIAL device.")):this.Id()};
g.h.T=function(){this.g();this.g=g.Ia;g.aq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;Y7.Ha.T.call(this)};
g.h.DM=function(a){this.ea()||a||(W7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Id())};
g.h.cq=function(a){this.H=X5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Cqa(this));a(b);Bqa(this)}else this.B=(0,g.y)(function(){g.aq(this.A);this.B=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Cqa(this));a(c);Bqa(this)},this),this.A=g.Zp((0,g.y)(function(){this.B()},this),100)};
g.h.ED=function(a,b,c){S7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.bn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.cq(b,c)},this),(0,g.y)(function(d){W7(this,"Failed to get DIAL screen: "+d);
this.cq(b,c)},this))};g.A(Z7,V7);Z7.prototype.stop=function(){this.Id()};
Z7.prototype.ls=g.Ia;Z7.prototype.bi=function(){g.aq(this.g);this.g=NaN;var a=Z5(this.F.Fd(),this.i.label);a?this.bn(a):this.Id(Error("No such screen"))};
Z7.prototype.T=function(){g.aq(this.g);this.g=NaN;Z7.Ha.T.call(this)};g.A($7,g.P);g.h=$7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.My,this),(0,g.y)(this.VJ,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.fI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),pqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.YA,this)),this.l=Eqa(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Og(f))},this)),this.N("yt-remote-cast2-availability-change",b8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Og(f));
b(!1)},this))};
g.h.ML=function(a,b){a8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)a8("Unsetting old screen status: "+this.g.i.friendlyName),c8(this,null)}if(a&&b){if(!this.g){c=Z5(this.i.Fd(),a);if(!c){a8("setConnectedScreenStatus: Unknown screen.");return}var d=Dqa(this,c);d||(a8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Og(e))},this)));
a8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);c8(this,new Z7(this.i,d),!0)}this.g.os(b)}else a8("setConnectedScreenStatus: no screen.")};
g.h.NL=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.bi(a):this.Jb("Setting connection data without a session")};
g.h.CM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),c8(this,null)):a8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.My,this),(0,g.y)(this.rK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.YA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],v7);g.rf(this.g);$7.Ha.T.call(this)};
g.h.Jb=function(a){z7("Controller",a)};
g.h.Ny=function(a,b){this.g==a&&(b||c8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.RJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),a8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)a8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{a8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:c8(this,
new Z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:c8(this,new Y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:c8(this,new X7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.fI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return a8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);c8(this,new Y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.ED,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.cq,b))};
g.h.My=function(a){if(!this.ea()){a8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)a8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),c8(this,new X7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=Z5(this.i.Fd(),c.label);d&&S5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(a8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.rf(this.g),this.g=new X7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Ny,this,this.g)),this.g.bi(null));this.g.ls(a)}}};
g.h.BM=function(){return this.g?this.g.ZA():null};
g.h.rK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Og(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&c8(this,null))};
g.h.VJ=function(a){a8("Receiver availability updated: "+a);if(!this.ea()){var b=b8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;b8(this)!=b&&this.N("yt-remote-cast2-availability-change",b8(this))}};
g.h.YA=function(){this.ea()||(this.l=Eqa(this),a8("Updating custom receivers: "+g.Og(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",b8(this)))};
$7.prototype.setLaunchParams=$7.prototype.NL;$7.prototype.setConnectedScreenStatus=$7.prototype.ML;$7.prototype.stopSession=$7.prototype.CM;$7.prototype.getCastSession=$7.prototype.BM;$7.prototype.requestSession=$7.prototype.requestSession;$7.prototype.init=$7.prototype.init;$7.prototype.dispose=$7.prototype.dispose;var i8=[];n8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ge=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
n8.prototype.isAdPlaying=function(){return 1081==this.playerState};
n8.prototype.getDuration=function(){return this.u?this.D+p8(this):this.D};
n8.prototype.clone=function(){return new n8(t8(this))};g.A(v8,g.P);g.h=v8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,B8(this,"play")):A8(this,"play"),z8(this,1,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,B8(this,"pause")):A8(this,"pause"),z8(this,2,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=w8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,B8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.N("remotePlayerChange")}else x8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,B8(this,"stopVideo")):A8(this,"stopVideo");var a=w8(this);a.index=-1;a.videoId="";o8(a);y8(this,a);this.N("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=w8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){z7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){z7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Ra(this.setVolume,a,b))};
g.h.Yz=function(a,b){if(1==this.g){var c=w8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Og(b.style),g.fc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Ra(this.Yz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=w8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=w8(this);c=c||0;var m={videoId:a,currentIndex:c};s8(l,a,c);g.Ea(b)&&(q8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Og(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.kn=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Ra(this.kn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Ra(this.nextVideo,a,b))};
g.h.Vu=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.Vu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}v8.Ha.dispose.call(this)};
g.h.T=function(){Rqa(this);this.o=null;this.u.clear();u8(this,null);v8.Ha.T.call(this)};
g.h.Zs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.OJ=function(a,b){this.N(a,b)};
g.h.LH=function(a){if(!a)this.lk(null),u8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=w8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)z7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.lk=function(a){z7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Sqa(this),this.N("remotePlayerChange")};
g.h.KH=function(a){a?(Sqa(this),this.N("remotePlayerChange")):this.lk(null)};
g.h.Is=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.XH=function(){var a=Oqa();a&&u8(this,a)};
g.h.Jb=function(a){z7("CP",a)};g.A(C8,g.P);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;q8(this.Qa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.Og(l));this.g.connect({method:"setPlaylist",
params:g.Og(l)},a,e6())}else D8("Connecting without params"),this.g.connect({},a,e6());Uqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),E8(this,3));C8.Ha.dispose.call(this)};
g.h.T=function(){F8(this);H8(this);G8(this);g.aq(this.F);this.F=NaN;g.aq(this.H);this.H=NaN;this.l=null;g.Wr(this.P);this.P.length=0;this.g.dispose();C8.Ha.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.RC=function(){this.A(2)};
g.h.PH=function(){D8("Channel opened");this.M&&(this.M=!1,G8(this),this.O=g.Zp((0,g.y)(function(){D8("Timing out waiting for a screen.");this.A(1)},this),15E3));
gqa(nqa(this.g),this.V)};
g.h.MH=function(){D8("Channel closed");isNaN(this.u)?h6(!0):h6();this.dispose()};
g.h.NH=function(a){h6();isNaN(this.D())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,D8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),E8(this,2))};
g.h.OH=function(a){a.params?D8("Received: action="+a.action+", params="+g.Og(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N5(a.params.devices);this.i=(0,g.G)(a,function(c){return new Q5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Xqa(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Xqa(this,!1);break;case "remoteConnected":var b=new Q5(N5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Vpa(this.i,b);
break;case "remoteDisconnected":b=new Q5(N5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Zqa(this,a);break;case "nowPlaying":ara(this,a);break;case "onStateChange":$qa(this,a);break;case "onAdStateChange":bra(this,a);break;case "onVolumeChanged":cra(this,a);break;case "onSubtitlesTrackChanged":Yqa(this,a);break;case "nowAutoplaying":dra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":era(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.BL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&I8(this,"getNowPlaying")}};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Bf;C8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?r7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
C8.prototype.getProxyState=C8.prototype.ca;C8.prototype.A=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&h6();q7(this.g,a);this.dispose()};
C8.prototype.disconnect=C8.prototype.A;C8.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),s8(a,this.l,a.index));return t8(a)};
C8.prototype.getPlayerContextData=C8.prototype.X;
C8.prototype.ka=function(a){var b=new n8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.aq(this.F),this.F=g.Zp((0,g.y)(this.BL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&r8(this.Qa)==r8(b)&&g.Og(this.Qa.g)==g.Og(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
C8.prototype.setPlayerContextData=C8.prototype.ka;C8.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
C8.prototype.getOtherConnectedRemoteId=C8.prototype.R;C8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
C8.prototype.getReconnectTimeout=C8.prototype.D;C8.prototype.aa=function(){return this.o||"UNSUPPORTED"};
C8.prototype.getAutoplayMode=C8.prototype.aa;C8.prototype.Y=function(){return this.B||""};
C8.prototype.getAutoplayVideoId=C8.prototype.Y;C8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.yo(a.g);a.start()}};
C8.prototype.reconnect=C8.prototype.va;C8.prototype.ia=function(a,b){I8(this,a,b);Wqa(this)};
C8.prototype.sendMessage=C8.prototype.ia;g.A(J8,D7);g.h=J8.prototype;g.h.Fd=function(a){return this.Gc.$_gs(a)};
g.h.contains=function(a){return!!this.Gc.$_c(a)};
g.h.get=function(a){return this.Gc.$_g(a)};
g.h.start=function(){this.Gc.$_st()};
g.h.add=function(a,b,c){this.Gc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Gc.$_r(a,b,c)};
g.h.Sn=function(a,b,c,d){this.Gc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Gc.$_ubk(this.i[a]);this.i.length=0;this.Gc=null;J8.Ha.T.call(this)};
g.h.yM=function(){this.N("screenChange")};
g.h.sJ=function(){this.N("onlineScreenChange")};
Q7.prototype.$_st=Q7.prototype.start;Q7.prototype.$_gspc=Q7.prototype.zM;Q7.prototype.$_gsppc=Q7.prototype.XA;Q7.prototype.$_c=Q7.prototype.contains;Q7.prototype.$_g=Q7.prototype.get;Q7.prototype.$_a=Q7.prototype.add;Q7.prototype.$_un=Q7.prototype.Sn;Q7.prototype.$_r=Q7.prototype.remove;Q7.prototype.$_gs=Q7.prototype.Fd;Q7.prototype.$_gos=Q7.prototype.WA;Q7.prototype.$_s=Q7.prototype.subscribe;Q7.prototype.$_ubk=Q7.prototype.Bf;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Jy,this);this.g.unsubscribe("remotePlayerChange",this.nk,this);this.g.unsubscribe("remoteQueueChange",this.cn,this);this.g.unsubscribe("autoplayUpNext",this.ky,this);this.g.unsubscribe("previousNextChange",this.Gy,this);this.g.unsubscribe("nowAutoplaying",this.Cy,this);this.g.unsubscribe("autoplayDismissed",this.jy,this);this.g=this.u=null};
g.h.jx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!w8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==w8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Aj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.JH=function(a){this.I.NC(a)};
g.h.hM=function(a){this.jx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.kA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||e9(this,a)};
g.h.yy=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.nk,this);var b=Math.round(a.volume);a=!!a.muted;var c=w8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.nk,this)}};
g.h.JI=function(){g.Yb(this.B)||qra(this,this.B);this.D=!1};
g.h.Jy=function(a,b){this.A.stop();2==b&&this.jA()};
g.h.nk=function(){if(d9(this)){this.o.stop();var a=w8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.rm=1;break;case 1082:case 1083:this.u.rm=0;break;default:this.u.rm=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.xC(8));this.iA();break;case 1085:case 3:c9(this,new g.xC(9));break;case 1083:case 0:c9(this,new g.xC(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.xC(4));break;case 2:c9(this,new g.xC(4));b9(this,r8(a));
break;case -1:c9(this,new g.xC(64));break;case -1E3:c9(this,new g.xC(128,{errorCode:"mdx.remoteerror",message:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=w8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,qra(this,a));a=w8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.O.isActive()||this.JA()}else pra(this)};
g.h.Gy=function(){this.i.N("mdxpreviousnextchange")};
g.h.cn=function(){d9(this)||pra(this)};
g.h.YB=function(){this.g.Vu()};
g.h.ky=function(a){a&&(a=g.Wq("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.TK,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.TK=function(a,b){var c=new g.jB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Cy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.jy=function(){this.i.N("mdxautoplaycanceled")};
g.h.pF=function(a,b){-1==w8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.JA=function(){if(d9(this)){var a=w8(this.g);this.l.Na(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.yy)}};
g.h.iA=function(){this.o.stop();if(!this.g.ea()){var a=w8(this.g);1==a.playerState&&c9(this,new g.xC(8));b9(this,r8(a));this.o.start()}};
g.h.jA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.W);g9.prototype.u=function(a){sra(this,a.state)};g.t(h9,g.UT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.VT(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.le=function(a){return"cast-selector-receiver"==a?"\u6295\u5c04\u2026":this.F[a].name};
h9.prototype.Ic=function(a){g.UT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.RK);g.h=i9.prototype;g.h.create=function(){jra(g.bz(g.X(this.player)));this.u.push(g.fq("yt-remote-before-disconnect",this.GH,this));this.u.push(g.fq("yt-remote-connection-change",this.WJ,this));this.u.push(g.fq("yt-remote-receiver-availability-change",this.Hy,this));this.u.push(g.fq("yt-remote-auto-connect",this.UJ,this));this.u.push(g.fq("yt-remote-receiver-resumed",this.TJ,this));this.Hy()};
g.h.load=function(){this.player.cancelPlayback();g.RK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=ora())?a.currentTime:0;var b=Z8()?new v8(U8(),void 0):null;0==a&&b&&(a=r8(w8(b)));0!=a&&this.nd(a);rra(this,this.Yj,this.Yj);g.UX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.sf(this.o,this.g);this.g=this.o=null;g.RK.prototype.unload.call(this);g.UX(this.player.app,5)};
g.h.T=function(){g.gq(this.u);g.RK.prototype.T.call(this)};
g.h.Re=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.jx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.rm};
g.h.JC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ge=function(){return this.g?w8(this.g).Ge:!1};
g.h.hasNext=function(){return this.g?w8(this.g).hasNext:!1};
g.h.nd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=w8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+p8(a):a.l,isAtLiveHead:1>=(a.u?a.i+p8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+p8(a):a.i,seekableStart:0<a.o?a.o+
p8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.kn=function(){this.g&&this.g.kn()};
g.h.GH=function(a){1==a&&(this.B=this.g?w8(this.g):null)};
g.h.WJ=function(){var a=Z8()?new v8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.rf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,r8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Hy=function(){this.A=[this.i].concat(lra());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.UJ=function(){var a=V8();j9(this,a)};
g.h.TJ=function(){this.l=V8()};
g.h.ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&l8(),!0):!1}};
g.h.Is=function(){this.g.Is()};
g.h.Mb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.kV.remote=i9;})(_yt_player);
